### ISSUE TITLE
Add capn' proto

### ISSUE THREAD

**Issue by pickfire** [llogiq/serdebench#2]
It is be good to compare capn' proto too.

**Comment by llogiq** [comment]
It is added. However, perf is...suboptimal. maybe we did something wrong?

**Comment by pickfire** [comment]
I just saw it. I am surprised it is slower.

**Comment by llogiq** [comment]
Me too, but I looked at the code and found no obvious error.

**Comment by pickfire** [comment]
Maybe it would be good to report it to capnp-rust?
